cc_test(
    name = "hello_test",
    size = "small",
    srcs = [
        "hello_test.cc",
    ],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "fav_test",
    size = "small",
    srcs = [
        "fav_test.cc",
    ],
    tags = [
        "exclusive",
    ],
    visibility = ["//visibility:public"],
    data = glob(["testcase/**"]),
    deps = [
        "@com_google_googletest//:gtest_main",
        "//:headers",
    ],
)
