cc_test(
    name = "hello_test",
    size = "small",
    srcs = [
        "hello_test.cc",
    ],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

LUACFLAGS = "-I/usr/include/lua5.1"
LUALIBS = "-llua5.1"

cc_test(
    name = "fav_test",
    size = "small",
    srcs = [
        "fav_test.cc",
    ],
    tags = [
        "exclusive",
    ],
    visibility = ["//visibility:public"],
    data = [
        "//testcase:testcase",
    ],
    copts = [
        "-Iinclude",
        "-Ibazel-out/k8-fastbuild/bin/include",
        "-Ibazel-out/k8-fastbuild/bin/common/fbs",
        LUACFLAGS,
        "-DBBSHOME=$(BBSHOME)",

        "-Itestutil",
    ],
    linkstatic = True,
    linkopts = [
        "-Os",
        "-Wl,--as-needed",
        "-Wl,--sort-common",

        "-Lbazel-out/k8-fastbuild/bin/common/bbs/_objs/commonbbs",
        "-Lbazel-out/k8-fastbuild/bin/common/sys/_objs/commonsys",
        "-Lbazel-out/k8-fastbuild/bin/common/osdep/_objs/commonosdep",
        "-Lbazel-out/k8-fastbuild/bin/testutil/_objs/testutil",

        LUALIBS,

        "-lstdc++",
    ],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//mbbsd:mbbsd",
        "//mbbsd:mbbsdcxx",
        "//testutil:testutil",
    ],
)
