SRCS = [
    "cpuload.c",
    "proctitle.c",
    "strlcat.c",
    "strlcpy.c",
    "memusage.c",
]

cc_library(
    name = "commonosdep",
    srcs = SRCS,
    linkstatic = True,
    copts = [
        "-Iinclude",
        "-Ibazel-out/k8-fastbuild/bin/include",
        "-DBBSHOME=$(BBSHOME)",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//include:all",
        "//:pttbbsconf",
    ],
)
