# $Id$

##########
# use googletest as test-framework
##########

TESTROOT:=	../..

SRCROOT:= ../../..
.include "$(SRCROOT)/pttbbs.mk"
.include "$(SRCROOT)/pttbbs_cond.mk"

##########
# test
##########

TEST_PROGS=	test_dummy test_pttui_thread_lock test_pttui_thread test_vedit3_buffer test_vedit3_resource_info

#######################################################################
# test
#######################################################################

.include "$(SRCROOT)/pttbbs_test.mk"
