PTT_WARN = [
    "-W",
    "-Wall",
    "-Wunused",
    "-Wno-missing-field-initializers",
    "-Wno-address-of-packed-member",
]

SRCS = [
    "load_uhash.c",
    "setup_root_link.c",
]

cc_library(
    name = "testutil",
    srcs = SRCS,
    hdrs = [
        "testutil.h",
        "mbbsd_s.c",
    ],
    visibility = ["//visibility:public"],
    linkstatic = True,
    copts = [
        "-Iinclude",
        "-Ibazel-out/k8-fastbuild/bin/include",
    ],
    deps = [
        "//include:all",
        "//:pttbbsconf",
        "//common/sys:commonsys",
        "//common/bbs:commonbbs",
    ],
    defines = [
        "BBSHOME='\"$(BINDIR)/testcase\"'",
    ],
)
