name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install pmake
      run: sudo apt update && sudo apt install -y pmake
    - name: pre-bazel
      run: sudo pmake pre-bazel
    - name: bazeltest
      run: sudo pmake bazeltest
